/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#3f79aa",
        "on-secondary": "#ffffff",
        "primary": "#206090",
        "on-error-container": "#93000a",
        "secondary": "#5e5e5e",
        "on-surface-variant": "#41474f",
        "tertiary-fixed-dim": "#c9c6c5",
        "primary-fixed": "#cee5ff",
        "tertiary-container": "#767474",
        "surface-dim": "#ddd9d9",
        "on-primary-fixed-variant": "#004a77",
        "tertiary-fixed": "#e6e1e1",
        "on-error": "#ffffff",
        "surface-variant": "#e6e1e1",
        "background": "#fdf8f8",
        "on-secondary-fixed-variant": "#474747",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#97cbff",
        "on-tertiary-fixed": "#1c1b1c",
        "on-secondary-fixed": "#1b1b1b",
        "outline-variant": "#c1c7d0",
        "surface-tint": "#246293",
        "secondary-fixed": "#e2e2e2",
        "error": "#ba1a1a",
        "surface": "#fdf8f8",
        "tertiary": "#5d5b5c",
        "on-primary-fixed": "#001d33",
        "on-tertiary-fixed-variant": "#484646",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-surface": "#1c1b1c",
        "on-background": "#1c1b1c",
        "error-container": "#ffdad6",
        "surface-bright": "#fdf8f8",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f4f0ef",
        "surface-container-high": "#ebe7e7",
        "on-tertiary-container": "#fffbff",
        "on-primary-container": "#fdfcff",
        "secondary-container": "#e2e2e2",
        "outline": "#717880",
        "surface-container": "#f1eded",
        "secondary-fixed-dim": "#c6c6c6",
        "inverse-primary": "#97cbff",
        "surface-container-low": "#f7f3f2",
        "surface-container-highest": "#e6e1e1",
        "on-secondary-container": "#646464"
      },
      fontFamily: {
        "headline": ["'Source Sans Pro'", "sans-serif"],
        "body": ["'Source Sans Pro'", "sans-serif"],
        "label": ["'Source Sans Pro'", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
}